### ISSUE TITLE
Coderoad validate keeps giving error

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-cli#72]
`coderoad validate` always gives me this error...

![Screen Shot 2020-08-10 at 3 28 40 PM](https://user-images.githubusercontent.com/20648924/89828215-60566d00-db1e-11ea-9eb6-e65d56d532be.png)

Not sure if I'm doing something wrong.

**Comment by ShMcK** [comment]
@moT01 I haven't been able to replicate the issue, but if you could:

1. test this version of the CLI in #73. To test: run `yarn && yarn build`. It should install the package locally.
2. then verify the `coderoad --version` you have locally is using 0.6.1. 
3. If so, try `coderoad validate` again.

If the issue persists, I'm guessing its because the temporary `.tmp` directory wasn't cleaned up. I'll have to look it to how that happens. You can safely erase it manually.

**Comment by moT01** [comment]
This seems to be fixed. I was able to run it without the error. I will keep an eye on it.
